export const FETCH_FILTERS = 'FETCH_FILTERS';
export type FETCH_FILTERS = typeof FETCH_FILTERS;

export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export type TOGGLE_FILTER = typeof TOGGLE_FILTER;

export const CLEAR_FILTER = 'CLEAR_FILTER';
export type CLEAR_FILTER = typeof CLEAR_FILTER;

export const FETCH_SENTENCE = 'FETCH_SENTENCE';
export type FETCH_SENTENCE = typeof FETCH_SENTENCE;

export const RECEIVE_FILTERS = 'RECEIVE_FILTERS';
export type RECEIVE_FILTERS = typeof RECEIVE_FILTERS;

export const RECEIVE_SENTENCE = 'RECEIVE_SENTENCE';
export type RECEIVE_SENTENCE = typeof RECEIVE_SENTENCE;
